### ISSUE TITLE
Create MySQL script for DB migration

### ISSUE THREAD

**Issue by FrancoAltavilla** [SepaSoporteIt/SEPA_APP_REACT#87]
[Data](https://docs.google.com/spreadsheets/d/19EXjiuUPlBC2Y9BBf73F0CQGZJPF2WQCWYInEX38KMo/edit?usp=sharing)

**Comment by juanpablomaggi** [comment]
This will do what you want:

INSERT INTO table2 (st_id,uid,changed,status,assign_status)
SELECT st_id,from_uid,now(),'Pending','Assigned'
FROM table1
If you want to include all rows from table1. Otherwise you can add a WHERE statement to the end if you want to add only a subset of table1.

I hope this helps.
